name = "SciMLOperators"
uuid = "c0aeaf25-5076-4817-a8d5-81caf7dfa961"
authors = ["Vedant Puri <vedantpuri@gmail.com>"]
version = "1.6.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[extensions]
SciMLOperatorsChainRulesCoreExt = "ChainRulesCore"
SciMLOperatorsSparseArraysExt = "SparseArrays"
SciMLOperatorsStaticArraysCoreExt = "StaticArraysCore"

[compat]
Accessors = "0.1.42"
ArrayInterface = "7.19"
ChainRulesCore = "1.26.0"
DocStringExtensions = "0.9.4"
LinearAlgebra = "1.10"
MacroTools = "0.5.16"
SparseArrays = "1.10"
StaticArraysCore = "1"
julia = "1.10"
